[package]
name = "adventofcode-2019"
version = "0.1.0"
authors = ["Harrison McCullough <harrison.mccullough@romariccorp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.10"
array2d = "0.2"
